### ISSUE TITLE
URL Hyperlinks are broken

### ISSUE THREAD

**Issue by DeceptiveScorpion** [henson/Scraper#3]
On 2023-04-16 the daily Scraper file's URLs show "github.com" instead of the direct link to respective repository.

How to replicate the issue:

1. Click on a hyperlink in a .md file created on or after 2023-04-16.
2. It will direct you to github.com instead of the repository

 Example: 

Before 2023-04-16

![image](https://user-images.githubusercontent.com/6787289/233760597-d5dc68a0-db65-4234-b5b2-bd54f662ee3b.png)

After 2023-04-16

![image](https://user-images.githubusercontent.com/6787289/233760561-58a1b8c7-3524-461c-8297-aa277f552617.png)

**Comment by henson** [comment]
Thanks for your feedback, Github tweaked the HTML code. Now it has been fixed.
