### ISSUE TITLE
Daily Files Not Being Generated in the Correct Directory

### ISSUE THREAD

**Issue by DeceptiveScorpion** [henson/Scraper#4]
It's me again. Thanks for fixing the hyperlink issue #3 . 

Issue: 

When the daily files are generated they are put on the root directory and not /year/month directory. This started on 2023-04-01.  

![image](https://user-images.githubusercontent.com/6787289/236760885-d6e7684d-2ac6-4cdc-b136-ed11773e903f.png)

**Comment by henson** [comment]
Today you will find that all the April files have been included in the corresponding folder, because the function collectDocs() collect the files made in last month will occur at `time.Now().Day() == 10 `
